---
title: "covid19_soc_swissix"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(statR)

```

## Data Import

```{r cars}

url_dat <- "https://raw.githubusercontent.com/CGRBZH/covid19_soc_swissix/master/Social_SWISSIX.csv"

data <- read_csv(url(url_dat))

```

## Visualization 1 - Daily volume

```{r vis daily, fig.height=8, fig.width=12, echo=FALSE}

ggplot(data, aes(x=date, y=value/8)) + geom_point(color = "#FF6666", alpha = 0.7) +
  geom_path(color = "#FF6666", alpha = 0.7) +
  scale_x_date(date_labels = "%a\n%d. %m", date_breaks = "1 week") +
  labs(title = "Tägliches Internet-Datenvolumen | 01.01.-05.04.2020",
       caption = "Quelle: SwissIX",
       x = NULL,
       y = "Terabyte") +
  theme_stat() +
  theme(panel.grid.major.x = element_line(linetype = "solid", size = 0.25, color = "grey"))

# ggsave("swissix_daily.png", width = 24, height = 8, units = "cm")

```

## Visualization 2 - Weekly Volume

```{r vis weekly, fig.height=8, fig.width=12}

# Data prep
data_wk <- data %>% select(date, value) %>%
  mutate(week = format(date, '%Y-%V')) %>%
  group_by(week) %>%
  summarise(weekly_total = sum(value)) %>%
  mutate(weekly_change = weekly_total - lag(weekly_total, default = first(weekly_total)))

ggplot(data_wk, aes(week)) + 
  geom_bar(aes(weight = weekly_total/8), fill = "#FF6666")+
  labs(title = "Wöchentliches Internet-Datenvolumen | KW 1- KW 14, 2020",
       caption = "Quelle: SwissIX",
       x = NULL,
       y = "Terabyte") +
  ylim(c(0, 15000)) +
  theme_stat()

# ggsave("swissix_weekly.png", width = 28, height = 18, units = "cm")

```

